export default {
  CONFIG_INIT: 'CONFIG_INIT',
  DEVICE_DETECT: 'DEVICE_DETECT',
  SLOTS_INIT: 'SLOTS_INIT',
  DATA_LOADING: 'DATA_LOADING',
  DATA_LOADING_ERROR: 'DATA_LOADING_ERROR',
  DATA_LOADED: 'DATA_LOADED',
  DATA_DELETE: 'DATA_DELETE',
  DATA_SYNC: 'DATA_SYNC',
  DATA_SIDE_SET: 'DATA_SIDE_SET',
  DATA_DATA_SET: 'DATA_DATA_SET',
  DATA_URL_SET: 'DATA_URL_SET',
  SCREEN_SIZE_ADD: 'SCREEN_SIZE_ADD',
  SCREEN_SIZE_CHANGE: 'SCREEN_SIZE_CHANGE',
  SCREEN_SIZES_CLEAR: 'SCREEN_SIZES_CLEAR',
  DATA_TOTAL_SET: 'DATA_TOTAL_SET',
  GRID_ROWSHEIGHT_SET: 'GRID_ROWSHEIGHT_SET',
  // select module
  SELECT_SELECT_ROW: 'SELECT_SELECT_ROW',
  SELECT_UNSELECT_ROW: 'SELECT_UNSELECT_ROW',
  SELECT_SET_MULTISELECT: 'SELECT_SET_MULTISELECT',
  // paginator module
  PAGINATOR_SET_PAGE: 'PAGINATOR_SET_PAGE',
  PAGINATOR_SET_PAGE_SIZE: 'PAGINATOR_SET_PAGE_SIZE',
  PAGINATOR_SET_PAGE_SIZES: 'PAGINATOR_SET_PAGE_SIZES',
  // filter module
  FILTER_SET_TEXT: 'FILTER_SET_TEXT',
  FILTER_ADD_COLUMN: 'FILTER_ADD_COLUMN',
  FILTER_COLUMN: 'FILTER_COLUMN',
  // sort module
  SORT: 'SORT',
  SORT_SET_MULTIPLE: 'SORT_SET_MULTIPLE',
  // main module
  COLUMNS_SET: 'COLUMNS_SET',
};
