export default {
  CONFIG_INIT: 'CONFIG_INIT',
  DEVICE_INIT: 'DEVICE_DETECT',
  SLOTS_INIT: 'SLOTS_INIT',
  DATA_LOADING: 'DATA_LOADING',
  DATA_LOADED: 'DATA_LOADED',
  DATA_DELETE: 'DATA_DELETE',
  DATA_SYNC: 'DATA_SYNC',
  DATA_SIDE_SET: 'DATA_SIDE_SET',
  DATA_DATA_SET: 'DATA_DATA_SET',
  DATA_URL_SET: 'DATA_URL_SET',
  SCREEN_SIZE_ADD: 'SCREEN_SIZE_ADD',
  SCREEN_SIZE_CHANGE: 'SCREEN_SIZE_CHANGE',
  SCREEN_SIZES_CLEAR: 'SCREEN_SIZES_CLEAR',
  DATA_TOTAL_SET: 'DATA_TOTAL_SET',
  ROW_SELECT: 'ROW_SELECT',
  ROW_UNSELECT: 'ROW_UNSELECT',
  GRID_ROWSHEIGHT_SET: 'GRID_ROWSHEIGHT_SET',
  // paginator module
  PAGINATOR_SET_PAGE: 'PAGINATOR_SET_PAGE',
  PAGINATOR_SET_PAGE_SIZE: 'PAGINATOR_SET_PAGE_SIZE',
  PAGINATOR_SET_PAGE_SIZES: 'PAGINATOR_SET_PAGE_SIZES',
  // filter module
  FILTER_SET_TEXT: 'FILTER_SET_TEXT',
  FILTER_ADD_COLUMN: 'FILTER_ADD_COLUMN',
  // sort module
  SORT_SET_FIELD: 'SORT_SET_FIELD',
};
