export default {
  CONFIG_INIT: 'CONFIG_INIT',
  DEVICE_INIT: 'DEVICE_DETECT',
  SLOTS_INIT: 'SLOTS_INIT',
  DATA_LOADING: 'DATA_LOADING',
  DATA_LOADED: 'DATA_LOADED',
  DATA_DELETE: 'DATA_DELETE',
  DATA_SYNC: 'DATA_SYNC',
  SCREEN_SIZE_ADD: 'SCREEN_SIZE_ADD',
  SCREEN_SIZE_CHANGE: 'SCREEN_SIZE_CHANGE',
  SCREEN_SIZES_CLEAR: 'SCREEN_SIZES_CLEAR',
  DATA_TOTAL_SET: 'DATA_TOTAL_SET',
  PAGE_SET: 'PAGE_SET',
};
